# 应用名称
spring:

  application:
    name: secret
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 数据源名称
    name: defaultDataSource
  # 数据库连接地址
    url: jdbc:mysql://localhost:3306/blue?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  # 数据库用户名&密码：
    username: root
    password: 123456
# 应用服务 WEB 访问端口
server:
  port: 8888
  servlet:
    context-path: /secretApi

com:
  cihai:
    secret-api:
      privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChlB68xGQ5LnP2Rx/QdDnXqw0iXDZq66gfyMV9XWUGDyvDrwMVtmIIIE7Vilrxco4Hi03WGF6C1qfFz72FebhYFqCjMjhQMP08JAIMf4xmIAKvapMDbs6B4Evg0hGDoI8EjDKa3EYiDetB8we+XFFcsO04IULl015IXmSCB/OkuAuv6w9ePEetPwcOpKJweQJW1mTIEbEngmYqy738TG1gVDbfy7wdHNbqZIRE2HramW7cCSlx6qTUmv2+gwNRpUh7egtWRF2S7zzovsJwPVQJdMYpHnjD2AD41OGpx0z2hKnD/AXDha+/i5LM/UiH5Q/JS5JO9qO9joY8dRpR8b+7AgMBAAECggEAA5eYa1fuZnsK5vHD2k2LL6lE3HuyVgQxM6uyAEyAP3c84NfWOLhaS5X0SrkNtop2b+J/83+NMll1V2d77ii7mXG/VoF6UQYVyy19witfwrF5fc7fv9bJzodfCHuDGisKou4+/cRh5sXqcgfmJyxEPsxMKdBLfXKKiQ9YKq/kkcfgo8r8nvIFuemA7JZM3kzhTwH+vJuqEUos16cL3mCEi5jtGTlLqvtBgpys9x8Mjsn4wT3Q0xqhCkpu1WJ9fkO/51yML6KTq10e/niYYNLbb8qvzB9lhg2NdZztch7nF9VTmDBubea1XfvNFoFSr1IV+05f7+4ovYwCD6MyXeI+0QKBgQDXW3/usQuyEwQ0o31xRxeRbJlMzteAoT1QKXzpTn/ApdlG9VEQY9aMNyDIhqSuJsmnWxYlKmQ198fViPFBQZgtcMXGCXSJ7GjckibwrYIC8yXczD+sWI0SACJiDE/TVTbvUeFcaFi5MI4xUtIWoxtyIcytspvl4BZ6LQ4wgzLoAwKBgQDAEmtoBiiPSeSUjhQi0vqMKzIRt8uNp8leEuXYHluJClesmFs9KFUj5JrH5vaJFcLbfxeNKqFKVJJM9pxSW7yalUFDr8ZJB+bGUWTkT8e+9qjxp4Kdx1kTUCEubn4dQaWuO0e1a9fgH2NzslJX6ISC4ONaR0wKWQheWgfbYsGH6QKBgQCDGME1NXOQMIFT5d5cEdHoBfsARb3sILtpTAgtIkskpBEzX+y8FHqrmneLemNPXG9PQGSntTmRnMd6VsW+WsbfipHqbyERQOfItfOceZL2Zru6wF9WdAVUWt6TXzlMxcgOQYL1tNOl0EgPAILBowL3JForttmuQw6Ly1ei8osPrwKBgAFmoP3rPZR993rV5nOykj0/e2gBrSxlUuSqwp5m6kf/mVAa9F9n0ecnHbHjj1zEmd07+hH/g5mlMEP7cHxxStjdydISkCGsOxSrN08q/cv4xJauoBdCgvXPGc7a43SXK/wvVoCOPs7Vq8YGQO9/NKg3t7DK4FUa/SKjCXeiKsMxAoGAPlxWE+LrGgtNrPok3v9arQNy1FVAFBbgMB9qtu924j2wunm+BOwkRlSsu6OpXX0MnnF9JDeE7NmncOfI3aLm4rVzrAwVzyDIh8ilmM0XzSaGREP7gkimjgFH7oehlPx1S3rsaX20PTcPxJHVjrJckqnEFcnioF9lpTiHeT/Mykk=
      publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoZQevMRkOS5z9kcf0HQ516sNIlw2auuoH8jFfV1lBg8rw68DFbZiCCBO1Ypa8XKOB4tN1hhegtanxc+9hXm4WBagozI4UDD9PCQCDH+MZiACr2qTA27OgeBL4NIRg6CPBIwymtxGIg3rQfMHvlxRXLDtOCFC5dNeSF5kggfzpLgLr+sPXjxHrT8HDqSicHkCVtZkyBGxJ4JmKsu9/ExtYFQ238u8HRzW6mSERNh62plu3Akpceqk1Jr9voMDUaVIe3oLVkRdku886L7CcD1UCXTGKR54w9gA+NThqcdM9oSpw/wFw4Wvv4uSzP1Ih+UPyUuSTvajvY6GPHUaUfG/uwIDAQAB


